# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-30 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('passwd', models.CharField(max_length=50)),
                ('registe_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
    ]
