# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-31 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0002_auto_20170530_0426'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChongQing_Lottery_Num',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(default='', max_length=50)),
                ('time_draw', models.CharField(default='', max_length=50)),
                ('registe_date', models.CharField(default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chongqing_num',
            },
        ),
    ]
