# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-31 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0003_chongqing_lottery_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chongqing_lottery_num',
            old_name='registe_date',
            new_name='num_data',
        ),
    ]
