# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-02 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0004_auto_20170531_0737'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(default='', max_length=50)),
                ('forecast_code', models.CharField(default='', max_length=50)),
                ('opentime', models.CharField(default='', max_length=50)),
                ('opencode', models.CharField(default='', max_length=50)),
                ('code', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'forecastone',
            },
        ),
    ]
