# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-16 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0005_forecastone'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyLostOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('put_in_phase', models.CharField(default='', max_length=50)),
                ('opentime', models.CharField(default='', max_length=50)),
                ('put_in_money', models.IntegerField()),
                ('back_status', models.IntegerField()),
                ('back_money', models.IntegerField()),
                ('forecastone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lottery.ForecastOne')),
            ],
            options={
                'db_table': 'money_lost_one',
            },
        ),
    ]
